DjangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),

]

first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('add_album/', views.album_form, name="album_form"),
    path('add_musician/', views.musician_form, name="musician_form"),
    path('add_list/<int:artist_id>/', views.album_list, name="album_list"),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name="edit_artist"),
    path('edit_album/<int:album_id>/', views.edit_album, name="edit_album"),
]

first_app/models.py
from django.db import models


# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)
    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + " Rating: " + str(self.num_stars)

first_app/forms.py
from django import forms
from first_app import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import *
from first_app import forms


# Create your views here.
def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'Title': 'This is Home Page!', 'musician_list': musician_list}
    return render(request, 'first_app/index.html', context=diction)


def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name', 'release_date')
    diction = {'Title': 'List of Albums', 'artist_info': artist_info, 'album_list': album_list}
    return render(request, 'first_app/album_list.html', context=diction)


def musician_form(request):
    form = forms.MusicianForm()
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'Title': "Add Musician", 'musician_form': form}
    return render(request, 'first_app/musicain_form.html', context=diction)


def album_form(request):
    form = forms.AlbumForm()
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'Title': 'Add Album', 'album_form': form}
    return render(request, 'first_app/album_form.html', context=diction)


def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)
    diction = {'edit_form': form}
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=artist_info)
        if form.is_valid():
            form.save(commit=True)
            return album_list(request, artist_id)
    return render(request, 'first_app/edit_artist.html', context=diction)


def edit_album(request, album_id):
    album_info = Album.objects.get(pk=3)
    form = forms.AlbumForm(instance=album_info)
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST, instance=album_info)
        if form.is_valid():
            form.save(commit=True)
    diction = {'edit_form': form}
    return render(request, 'first_app/edit_album.html', context=diction)

templates/first_app/album_form.html
{% extends 'first_app/base.html' %}
{% block body %}
    <h3>Album Form :</h3>
    <form method="POST">
        {{ album_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Add" class="btn btn-primary btn-small">
    </form>
{% endblock %}

templates/first_app/album_list.html
{% extends 'first_app/base.html' %}
{% block body %}

    <h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }}</h4>
    <h4>instrument: {{ artist_info.instrument }}</h4>
    <a href="{% url 'first_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary">Edit</a>
    <h3>Album List</h3>
    <table class="table">
        <tr>
            <th> Album Name</th>
            <th> Relese Date</th>
            <th> Rating</th>
        </tr>
        {% for album in album_list %}
        <tr>
            <th><a href="{% url 'first_app:edit_album' album_id=album.id %}"> {{ album.name }}</a></th>
            <th> {{ album.release_date }}</th>
            <th> {{ album.num_stars }}</th>
        </tr>
    {% endfor %}

    </table>

{% endblock %}

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax. googleapis. com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs. cloudflare. com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>{{ Title }}</title>

</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav ">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'first_app:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:musician_form' %}">Add Musician</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:album_form' %}">Add Album</a>
        </li>
    </ul>
</nav>
<div class="container">
    {% block body %}

    {% endblock %}

</div>


{% block base %}
{% endblock %}
</body>
</html>

templates/first_app/edit_album.html
{% extends 'first_app/base.html' %}
{% block body %}
    <form class="" action = "index.html"method="POST">
    {{ edit_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="update" class="btn btn-success">
    </form>

{% endblock %}

templates/first_app/edit_artist.html
{% extends 'first_app/base.html' %}
{% block body %}
    <h3>Edit Artist</h3>
    <form method="POST">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Update" class="btn btn-primary btn-small">
    </form>
{% endblock %}

templates/first_app/musicain_form.html
{% extends 'first_app/base.html' %}
{% block body %}
    <h3>Musicain Form :</h3>
    <form method="POST">
        {{ musician_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Add" class="btn btn-primary btn-small">
    </form>
{% endblock %}